services:
  proxy:
    image: nginx:alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./core/backend/static:/usr/src/app/static
    ports:
      - 8088:8088
      - 8080:8080
    networks:
      - net
    depends_on:
      - orm
      - site

  site:
    build: ./core/frontend/
    restart: always
    depends_on:
      - orm
    volumes:
      - ./core/frontend:/usr/src/app
    networks:
      - net
    ports:
      - 8081:8000

  orm:
    build: ./core/backend/
    restart: always
    volumes:
      - ./core/backend:/usr/src/app
      - ./core/backend/static:/usr/src/app/static
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - net
    ports:
      - 8000:8000

  redis:
    image: redis
    networks:
      - net

  db:
    image: postgres:alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dmebel
      - POSTGRES_PASSWORD=Dmebel@192168
      - POSTGRES_DB=main_db
    networks:
      - net

volumes:
  postgres_data:

networks:
  net:
    driver: bridge
