# Generated by Django 4.2 on 2023-04-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50, verbose_name='Наименование бота')),
                ('tgbot_token', models.CharField(max_length=50, verbose_name='Telegram API токен')),
                ('start_message', models.TextField(verbose_name='Текст приветственного сообщения на команду "/start"')),
                ('active', models.BooleanField(default=False, verbose_name='Работает')),
            ],
        ),
    ]
