# Generated by Django 4.2 on 2023-04-15 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bot',
            options={'verbose_name': 'Телеграм бот', 'verbose_name_plural': 'Телеграм боты'},
        ),
    ]
