# Generated by Django 4.2 on 2023-05-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_alter_bot_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bot',
            options={'verbose_name': 'Бот', 'verbose_name_plural': 'Боты'},
        ),
        migrations.AddField(
            model_name='bot',
            name='bot_type',
            field=models.CharField(choices=[('tg', 'Телеграм'), ('vk', 'Вконтакте')], default='tg', max_length=3, verbose_name='Тип бота'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='tgbot_token',
            field=models.CharField(max_length=50, verbose_name='Bot API токен'),
        ),
    ]
