# Generated by Django 4.2 on 2023-04-12 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('res', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=150, verbose_name='Наименование')),
                ('details', models.TextField(verbose_name='Детали')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='res.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Предзаказ',
                'verbose_name_plural': 'Предзаказы',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('preorder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.preorder')),
            ],
            bases=('crm.preorder',),
        ),
    ]
