# Generated by Django 4.2 on 2023-04-14 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
        ('res', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100, verbose_name='Наименование')),
                ('number', models.CharField(max_length=50, verbose_name='Номер договора')),
                ('date', models.DateField(verbose_name='Дата')),
                ('amount', models.FloatField(default=250000, verbose_name='Сумма')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
            },
        ),
        migrations.CreateModel(
            name='PreOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=150, verbose_name='Наименование')),
                ('details', models.TextField(verbose_name='Детали')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='res.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Предзаказ',
                'verbose_name_plural': 'Предзаказы',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('preorder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.preorder')),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.contract', verbose_name='Договор')),
                ('preorder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_preorder', to='crm.preorder', verbose_name='Предзаказ')),
                ('prod_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.productiontype', verbose_name='Тип продукции')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.orderstatus', verbose_name='Статус заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
            bases=('crm.preorder',),
        ),
    ]
