# Generated by Django 4.2 on 2023-04-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
        ('res', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='tag',
            field=models.ManyToManyField(blank=True, to='data.tag', verbose_name='Тэг'),
        ),
    ]
