# Generated by Django 4.2 on 2023-04-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_employeegroup_employeerole_group'),
        ('res', '0002_alter_employee_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='tag',
            field=models.ManyToManyField(blank=True, to='data.tag', verbose_name='Тэг'),
        ),
    ]
