# Generated by Django 4.2 on 2023-04-15 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_employeegroup_employeerole_group'),
        ('res', '0003_client_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.contactmethod', verbose_name='Предпочтительный способ связи'),
        ),
    ]
